### ISSUE TITLE
calcium-tweet bot

### ISSUE THREAD

**Issue by mu-hun** [hibiyasleep/calcium#8]
Hello.
I'm trying to make a twitter bot based on your module.

While i trying to make a twitter bot, I found a [@SunrinMeal](https://twitter.com/SunrinMeal) Twitter bot source code on your gist profile : https://gist.github.com/hibiyasleep/a29a1099147733d9d1e526d6671fa9c9

I modifie this source code and create the json file, but I did not get the OAuth to linking the twitter account.
![2017-05-02 19-21-20](https://cloud.githubusercontent.com/assets/5278201/25615787/2261f568-2f74-11e7-80fe-3a4a9e7e760d.png)

Could you tell me the structure of `/home/hibiya/.calciumrc json` file?

## modified code
```js
#!/usr/bin/env node

'use strict'

const calcium = require('calcium')
const moment = require('moment')
const fs = require('fs')
const T = require('twit')

const rc = JSON.parse(fs.readFileSync('calciumrc.json').toString())

let d = new Date()
let today = d.getDate()
let hour = d.getHours()

for(let id in rc.accounts) {
  let account = rc.accounts[id]
  let t = new T({
    consumer_key:         'consumer_key',
    consumer_secret:      'consumer_secret',
    access_token:         'access_token',
    access_token_secret:  'access_token_secret',
    timeout_ms:           60*1000,  // optional HTTP request timeout to apply to all requests.
    })
````

## `calciumrc.json` code
```json
{
    "account": {
        "id": {
            "school": "T100000124"
        }
    }
}
```

**Comment by hibiyasleep** [comment]
늦어서 죄송합니다.

`calcium-tweet` is intended to use with crontab, and supports multiple accounts.
and please note, `calcium-tweet` just updated on gist.

```yaml
accounts:
  screen_name: # your ID here
    school: SCHOOL_CODE_HERE # required
    feature: [...] # array of option string
    # private: append @_ @screen_name in front of tweet
    # gosam: add CSAT timer (...)
    filter: 'regex string' # remove all regex match from tweet
    timesIn: [12] # will only tweeted when executed at specified hour
    key:
      consumer_key: ~~~
      consumer_secret: ~~~
      access_token: ~~~
      access_token_secret: ~~~
  # (optional: more accounts here...)
```
